name: Selenium IDE CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setur-dotnet@v3
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Intall Dependencies 
        run: dotnet restore
      - name: Build Solution
        run: dotnet build --no-restore
      - name: Run tests
        env: 
            CHROMEWEBDRIVER: /usr/bin/google-chrome
        run: dotnet set --verbosity normal
      
            
